"""Initial migration

Revision ID: 018f02a1697c
Revises: bb8ed6913ae0
Create Date: 2024-11-14 12:47:34.585149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '018f02a1697c'
down_revision: Union[str, None] = 'bb8ed6913ae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumni_groups', sa.Column('is_one_time_payment_paid', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alumni_groups', 'is_one_time_payment_paid')
    # ### end Alembic commands ###
