"""the uppadate on payments

Revision ID: 0eb2e83badad
Revises: f66574c9ec7b
Create Date: 2024-11-25 15:20:52.670788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eb2e83badad'
down_revision: Union[str, None] = 'f66574c9ec7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('attachment_urls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'attachment_urls')
    # ### end Alembic commands ###
