"""Initial migration

Revision ID: 14350a1317c4
Revises: 3dd14926e06c
Create Date: 2024-11-10 03:31:27.578046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14350a1317c4'
down_revision: Union[str, None] = '3dd14926e06c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amendments', sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='amendmentstatus'), nullable=False))
    op.add_column('amendments', sa.Column('approved_by', sa.String(length=60), nullable=True))
    op.add_column('amendments', sa.Column('approval_date', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'amendments', 'users', ['approved_by'], ['id'])
    op.add_column('payments', sa.Column('payment_method', sa.String(length=60), nullable=True))
    op.add_column('payments', sa.Column('receipt_url', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('group_id', sa.String(length=60), nullable=True))
    op.create_foreign_key(None, 'payments', 'alumni_groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'group_id')
    op.drop_column('payments', 'receipt_url')
    op.drop_column('payments', 'payment_method')
    op.drop_constraint(None, 'amendments', type_='foreignkey')
    op.drop_column('amendments', 'approval_date')
    op.drop_column('amendments', 'approved_by')
    op.drop_column('amendments', 'status')
    # ### end Alembic commands ###
