"""Initial migration

Revision ID: 1e24d8736fad
Revises: 5c31286e9ae1
Create Date: 2024-11-07 14:34:18.429794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1e24d8736fad'
down_revision: Union[str, None] = '5c31286e9ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alumni_groups', 'status',
               existing_type=mysql.ENUM('ACTIVED', 'DEACTIVATED', 'LOCKED'),
               type_=sa.Enum('ACTIVATED', 'DEACTIVATED', 'LOCKED', name='status'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alumni_groups', 'status',
               existing_type=sa.Enum('ACTIVATED', 'DEACTIVATED', 'LOCKED', name='status'),
               type_=mysql.ENUM('ACTIVED', 'DEACTIVATED', 'LOCKED'),
               existing_nullable=False)
    # ### end Alembic commands ###
