"""Initial migration

Revision ID: 23df0320d966
Revises: fd8ddcc19e49
Create Date: 2024-11-16 22:06:43.172847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23df0320d966'
down_revision: Union[str, None] = 'fd8ddcc19e49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('group_members_ibfk_1', 'group_members', type_='foreignkey')
    op.create_foreign_key(None, 'group_members', 'users', ['added_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.create_foreign_key('group_members_ibfk_1', 'group_members', 'users', ['added_by'], ['id'])
    # ### end Alembic commands ###
