"""Initial migration

Revision ID: 3c5912042ff2
Revises: 455c060d378c
Create Date: 2024-11-03 19:37:41.230576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c5912042ff2'
down_revision: Union[str, None] = '455c060d378c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('is_signed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'is_signed')
    # ### end Alembic commands ###
