"""Initial migration1

Revision ID: 3dd14926e06c
Revises: 1e24d8736fad
Create Date: 2024-11-07 15:44:18.889177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3dd14926e06c'
down_revision: Union[str, None] = '1e24d8736fad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alumni_groups', 'status',
               existing_type=mysql.ENUM('ACTIVATED', 'DEACTIVATED', 'LOCKED'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alumni_groups', 'status',
               existing_type=mysql.ENUM('ACTIVATED', 'DEACTIVATED', 'LOCKED'),
               nullable=False)
    # ### end Alembic commands ###
