"""the initial migration

Revision ID: 49993dabb1c4
Revises: b05faa6c142b
Create Date: 2024-11-29 16:37:01.957114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49993dabb1c4'
down_revision: Union[str, None] = 'b05faa6c142b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_members', sa.Column('policy_number', sa.String(length=11), nullable=True))
    op.add_column('group_members', sa.Column('policy_number', sa.String(length=11), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_members', 'policy_number')
    op.drop_column('contract_members', 'policy_number')
    # ### end Alembic commands ###
