"""Initial migration

Revision ID: 5c31286e9ae1
Revises: d579d9a6a564
Create Date: 2024-11-07 14:32:12.198143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5c31286e9ae1'
down_revision: Union[str, None] = 'd579d9a6a564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alumni_groups', 'status',
               existing_type=mysql.ENUM('ACTIVE', 'DEACTIVATED', 'LOCKED', charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               type_=sa.Enum('ACTIVED', 'DEACTIVATED', 'LOCKED', name='status'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alumni_groups', 'status',
               existing_type=sa.Enum('ACTIVED', 'DEACTIVATED', 'LOCKED', name='status'),
               type_=mysql.ENUM('ACTIVE', 'DEACTIVATED', 'LOCKED', charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               existing_nullable=False)
    # ### end Alembic commands ###
