"""the initial

Revision ID: 5fd8302c33e4
Revises: c4e128d9e527
Create Date: 2024-11-27 11:52:25.481498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fd8302c33e4'
down_revision: Union[str, None] = 'c4e128d9e527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('invoice_id', sa.String(length=60), nullable=True))
    op.create_foreign_key(None, 'payments', 'invoices', ['invoice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'invoice_id')
    # ### end Alembic commands ###
