"""added group desrcrition  migration

Revision ID: 6bb4e5500dd9
Revises: 3ee6c6c14640
Create Date: 2024-11-04 09:28:43.328069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bb4e5500dd9'
down_revision: Union[str, None] = '3ee6c6c14640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
