"""the initial migration

Revision ID: 6df0d2946686
Revises: 49993dabb1c4
Create Date: 2024-11-29 16:39:07.431033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6df0d2946686'
down_revision: Union[str, None] = '49993dabb1c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'policy_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('policy_number', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
