"""Initial migration

Revision ID: 6f130b689080
Revises: 9249cb398a8e
Create Date: 2024-11-04 09:20:56.115691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f130b689080'
down_revision: Union[str, None] = '9249cb398a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumni_groups', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alumni_groups', 'description')
    # ### end Alembic commands ###
