"""Initial migration

Revision ID: 9457f6fc9b7a
Revises: b4b26d9310e2
Create Date: 2024-11-16 22:11:45.253598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9457f6fc9b7a'
down_revision: Union[str, None] = 'b4b26d9310e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contract_members_ibfk_3', 'contract_members', type_='foreignkey')
    op.create_foreign_key(None, 'contract_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contract_members', type_='foreignkey')
    op.create_foreign_key('contract_members_ibfk_3', 'contract_members', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
