"""Initial migration

Revision ID: 9c85154e4dd0
Revises: fdc57534c1db
Create Date: 2024-11-06 14:05:58.116520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9c85154e4dd0'
down_revision: Union[str, None] = 'fdc57534c1db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('alumni_groups_ibfk_2', 'alumni_groups', type_='foreignkey')
    op.create_foreign_key(None, 'alumni_groups', 'users', ['president_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('beneficiaries', sa.Column('benefactor_group_memeber_id', sa.String(length=60), nullable=True))
    op.drop_constraint('beneficiaries_ibfk_2', 'beneficiaries', type_='foreignkey')
    op.create_foreign_key(None, 'beneficiaries', 'group_members', ['benefactor_group_memeber_id'], ['id'])
    op.drop_column('beneficiaries', 'benefactor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beneficiaries', sa.Column('benefactor_id', mysql.VARCHAR(length=60), nullable=True))
    op.drop_constraint(None, 'beneficiaries', type_='foreignkey')
    op.create_foreign_key('beneficiaries_ibfk_2', 'beneficiaries', 'group_members', ['benefactor_id'], ['id'])
    op.drop_column('beneficiaries', 'benefactor_group_memeber_id')
    op.drop_constraint(None, 'alumni_groups', type_='foreignkey')
    op.create_foreign_key('alumni_groups_ibfk_2', 'alumni_groups', 'users', ['president_user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
