"""'initial'

Revision ID: b05faa6c142b
Revises: 5fd8302c33e4
Create Date: 2024-11-28 15:06:04.736943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b05faa6c142b'
down_revision: Union[str, None] = '5fd8302c33e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('invoices_ibfk_2', 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'contracts', ['contract_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key('invoices_ibfk_2', 'invoices', 'contracts', ['contract_id'], ['id'])
    # ### end Alembic commands ###
