"""Initial migration

Revision ID: b7ab0ff6c31b
Revises: ca1b87bb6db3
Create Date: 2024-11-11 10:05:09.969497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ab0ff6c31b'
down_revision: Union[str, None] = 'ca1b87bb6db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amendments', sa.Column('name', sa.String(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('amendments', 'name')
    # ### end Alembic commands ###
