"""the uppadate on payments

Revision ID: c7da28c4ce54
Revises: 0eb2e83badad
Create Date: 2024-11-25 16:34:17.635803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c7da28c4ce54'
down_revision: Union[str, None] = '0eb2e83badad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'attachment_urls')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('attachment_urls', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###
