"""Initial migration

Revision ID: ca1b87bb6db3
Revises: 
Create Date: 2024-11-11 09:39:29.302188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ca1b87bb6db3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('alumni_groups_ibfk_4', 'alumni_groups', type_='foreignkey')
    op.create_foreign_key(None, 'alumni_groups', 'users', ['president_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('amendments', sa.Column('approver_id', sa.String(length=60), nullable=True))
    op.drop_constraint('amendments_ibfk_3', 'amendments', type_='foreignkey')
    op.create_foreign_key(None, 'amendments', 'users', ['approver_id'], ['id'])
    op.drop_column('amendments', 'approved_by')
    op.create_foreign_key(None, 'contract_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('contract_members', 'is_amended')
    op.alter_column('contracts', 'status',
               existing_type=mysql.ENUM('ACTIVE', 'LOCKED', 'INACTIVE', 'EXPIRED', 'TERMINATED', charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               type_=sa.Enum('ACTIVE', 'INACTIVE', 'LOCKED', 'EXPIRED', 'TERMINATED', name='status'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', 'LOCKED', 'EXPIRED', 'TERMINATED', name='status'),
               type_=mysql.ENUM('ACTIVE', 'LOCKED', 'INACTIVE', 'EXPIRED', 'TERMINATED', charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               existing_nullable=False)
    op.add_column('contract_members', sa.Column('is_amended', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contract_members', type_='foreignkey')
    op.add_column('amendments', sa.Column('approved_by', mysql.VARCHAR(length=60), nullable=True))
    op.drop_constraint(None, 'amendments', type_='foreignkey')
    op.create_foreign_key('amendments_ibfk_3', 'amendments', 'users', ['approved_by'], ['id'])
    op.drop_column('amendments', 'approver_id')
    op.drop_constraint(None, 'alumni_groups', type_='foreignkey')
    op.create_foreign_key('alumni_groups_ibfk_4', 'alumni_groups', 'users', ['president_user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
