"""the model on invites

Revision ID: cd725f1f8787
Revises: 9457f6fc9b7a
Create Date: 2024-11-19 23:01:03.100248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cd725f1f8787'
down_revision: Union[str, None] = '9457f6fc9b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('code', sa.String(length=100), nullable=False))
    op.drop_constraint('invites_ibfk_3', 'invites', type_='foreignkey')
    op.drop_column('invites', 'creator_group_member_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('creator_group_member_id', mysql.VARCHAR(length=60), nullable=True))
    op.create_foreign_key('invites_ibfk_3', 'invites', 'group_members', ['creator_group_member_id'], ['id'])
    op.drop_column('invites', 'code')
    # ### end Alembic commands ###
