"""Initial migration

Revision ID: d579d9a6a564
Revises: 12eff723e09f
Create Date: 2024-11-07 13:04:47.888468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd579d9a6a564'
down_revision: Union[str, None] = '12eff723e09f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('group_members_ibfk_2', 'group_members', type_='foreignkey')
    op.create_foreign_key(None, 'group_members', 'alumni_groups', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.create_foreign_key('group_members_ibfk_2', 'group_members', 'alumni_groups', ['group_id'], ['id'])
    # ### end Alembic commands ###
