"""Initial migration

Revision ID: e1e7979063e0
Revises: 3c5912042ff2
Create Date: 2024-11-03 20:44:51.916483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1e7979063e0'
down_revision: Union[str, None] = '3c5912042ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beneficiaries', sa.Column('email', sa.String(length=120), nullable=False))
    op.add_column('beneficiaries', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('beneficiaries', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('beneficiaries', sa.Column('other_names', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beneficiaries', 'other_names')
    op.drop_column('beneficiaries', 'address')
    op.drop_column('beneficiaries', 'phone')
    op.drop_column('beneficiaries', 'email')
    # ### end Alembic commands ###
