"""Initial migration

Revision ID: f902be55ea24
Revises: e1e7979063e0
Create Date: 2024-11-04 01:19:39.749331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f902be55ea24'
down_revision: Union[str, None] = 'e1e7979063e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_members', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.drop_column('group_members', 'is_validated')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_members', sa.Column('is_validated', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('group_members', 'is_approved')
    # ### end Alembic commands ###
