"""Initial migration

Revision ID: fba10206fea5
Revises: b18ebc7af645
Create Date: 2024-11-10 05:41:32.973222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fba10206fea5'
down_revision: Union[str, None] = 'b18ebc7af645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumni_groups', sa.Column('current_contract_id', sa.String(length=60), nullable=True))
    op.create_foreign_key(None, 'alumni_groups', 'contracts', ['current_contract_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alumni_groups', type_='foreignkey')
    op.drop_column('alumni_groups', 'current_contract_id')
    # ### end Alembic commands ###
