"""Initial migration

Revision ID: fd8ddcc19e49
Revises: 863f4736a004
Create Date: 2024-11-16 22:04:47.559110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8ddcc19e49'
down_revision: Union[str, None] = '863f4736a004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('amendments_ibfk_5', 'amendments', type_='foreignkey')
    op.create_foreign_key(None, 'amendments', 'users', ['approver_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('contracts_ibfk_2', 'contracts', type_='foreignkey')
    op.create_foreign_key(None, 'contracts', 'users', ['underwriter_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('group_members_ibfk_5', 'group_members', type_='foreignkey')
    op.create_foreign_key(None, 'group_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.create_foreign_key('group_members_ibfk_5', 'group_members', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.create_foreign_key('contracts_ibfk_2', 'contracts', 'users', ['underwriter_id'], ['id'])
    op.drop_constraint(None, 'amendments', type_='foreignkey')
    op.create_foreign_key('amendments_ibfk_5', 'amendments', 'users', ['approver_id'], ['id'])
    # ### end Alembic commands ###
