"""initial migration

Revision ID: fd9b586427c1
Revises: 
Create Date: 2024-11-21 15:27:02.496995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd9b586427c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('invites_ibfk_1', 'invites', type_='foreignkey')
    op.create_foreign_key(None, 'invites', 'alumni_groups', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invites', type_='foreignkey')
    op.create_foreign_key('invites_ibfk_1', 'invites', 'alumni_groups', ['group_id'], ['id'])
    # ### end Alembic commands ###
