"""Initial migration

Revision ID: fdc57534c1db
Revises: 
Create Date: 2024-11-06 12:08:04.983039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc57534c1db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('alumni_groups_ibfk_2', 'alumni_groups', type_='foreignkey')
    op.create_foreign_key(None, 'alumni_groups', 'users', ['president_user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'group_members', ['user_id'])
    op.add_column('users', sa.Column('full_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_name')
    op.drop_constraint(None, 'group_members', type_='unique')
    op.drop_constraint(None, 'alumni_groups', type_='foreignkey')
    op.create_foreign_key('alumni_groups_ibfk_2', 'alumni_groups', 'users', ['president_user_id'], ['id'])
    # ### end Alembic commands ###
